### ISSUE TITLE
Click on column headers to sort by that column

### ISSUE THREAD

**Issue by roncli** [ezio416/tm-tmtracker#5]
I'd like to see a way to sort by a column when you click on the column header, for instance clicking on "Delta to AT" sorts the column by that delta time.  Clicking on the column again should reverse the sort.

**Comment by ezio416** [comment]
Agreed, I just need to find some way to do this efficiently.

**Comment by ezio416** [comment]
I'm nearly done with the implementation, will be in the next version

**Comment by ezio416** [comment]
added in version 3.3.0
